name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/*/package*.json') }}
          restore-keys: npm-

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: Cache outputs
        uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: gatsby-${{ runner.os }}
          restore-keys: gatsby-

      - name: Create public folder
        run: mkdir -p public

      - name: Run npm install
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public
        
        
        
        
        
        
        
        
        
        
